### ISSUE TITLE
Placing Grass Covering on grass block crashes server. Minecraft 1.16.2, Trapcraft 3.1.0

### ISSUE THREAD

**Issue by DrToxic** [percivalalb/Trapcraft#11]
Server log:

[23Dec2020 23:07:46.202] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: Encountered an unexpected exception
java.lang.NoSuchMethodError: net.minecraft.block.Block.func_176225_a(Lnet/minecraft/block/BlockState;Lnet/minecraft/world/IBlockReader;Lnet/minecraft/util/math/BlockPos;Lnet/minecraft/util/Direction;)Z
	at trapcraft.block.GrassCoveringBlock.func_196260_a(GrassCoveringBlock.java:51) ~[?:3.1.0]
	at net.minecraft.block.AbstractBlock$AbstractBlockState.func_196955_c(AbstractBlock.java:667) ~[?:?]
	at net.minecraft.item.BlockItem.func_195944_a(BlockItem.java:141) ~[?:?]
	at net.minecraft.item.BlockItem.func_195945_b(BlockItem.java:106) ~[?:?]
	at net.minecraft.item.BlockItem.func_195942_a(BlockItem.java:51) ~[?:?]
	at net.minecraft.item.BlockItem.func_195939_a(BlockItem.java:39) ~[?:?]
	at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:588) ~[?:?]
	at net.minecraft.item.ItemStack.func_196084_a(ItemStack.java:184) ~[?:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_219441_a(PlayerInteractionManager.java:350) ~[?:?]
	at net.minecraft.network.play.ServerPlayNetHandler.func_184337_a(ServerPlayNetHandler.java:889) ~[?:?]
	at net.minecraft.network.play.client.CPlayerTryUseItemOnBlockPacket.func_148833_a(SourceFile:36) ~[?:?]
	at net.minecraft.network.play.client.CPlayerTryUseItemOnBlockPacket.func_148833_a(SourceFile:10) ~[?:?]
	at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) ~[?:?]
	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:729) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:156) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:712) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:706) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:692) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:641) ~[?:?]
	at net.minecraft.server.MinecraftServer.lambda$func_240784_a_$0(MinecraftServer.java:229) ~[?:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_271]

**Comment by percivalalb** [comment]
This was fixed in v3.2.1, please update

**Comment by DrToxic** [comment]
v3.2.1 crashes the server on startup
v.3.2.2 has the same result.

as I said in the title, **server is 1.16.2**
v3.2.1 and above are **server 1.16.3** mods and expect **FML34**. Server has **FML33**.

**Comment by percivalalb** [comment]
This is a different problem tho? You should update your server to 1.16.4, mods should be targeting that now.

I have updated the supported versions for v3.2.2 (should only work on MC 1.16.3 & 1.16.4). Sorry I can't support all sub-versions.
